sudo: required

language: node_js
node_js:
  - "7"

addons:
  chrome: stable

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  global:
    - SELENIUM_MAJOR_VERSION=3.12
    - SELENIUM_VERSION=3.12.0
    - CHROMEDRIVER_VERSION=2.38
    - CHROMEDRIVER_FILE="chromedriver_linux64.zip"
    - SELENIUM_INSTALL_BIN=true

before_script:
  - ./run-selenium.sh
  - npm install -g selenium-webdriver http-server
  - http-server

script:
  - npm run selenium-tests